[buildPlans.iosevka-web-fixed]
family = "Iosevka Web Fixed"
spacing = "fixed"
serifs = "sans"

[buildPlans.iosevka-web-fixed.variants.design]
capital-q = "straight"
l = "serifed-tailed"
one = "base"
six = "closed-contour"
seven = "serifed"
nine = "closed-contour"
tilde = "high"
number-sign = "slanted"
ampersand = "et-toothed"
at = "fourfold"
dollar = "open"
percent = "rings-segmented-slash"
