[buildPlans.iosevka-cherrypick]
family = "Iosevka CherryPick"
design = ["sans", "sp-fixed", "leading-1250",
		  "cv08", "cv69", "cv43", "cv51", "cv65",
          "cv16", "cv45", "cv32", "cv38"]

[buildPlans.iosevka-cherrypick.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-cherrypick.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-cherrypick.weights.bold]
shape = 700
menu  = 700
css   = 700

