" ln -s ~/.vimrc.d/vimrc ~/.vimrc
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

source $REPO/dotfiles/vimrc/editor.vim
source $REPO/dotfiles/vimrc/plugins.vim
source $REPO/dotfiles/vimrc/shortcuts.vim
source $REPO/dotfiles/vimrc/filetype.vim

