" ln -s ~/.vimrc.d/vimrc ~/.vimrc
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

source $DOTFILES/vimrc/editor.vim
source $DOTFILES/vimrc/plugins.vim
source $DOTFILES/vimrc/plugins-config.vim
source $DOTFILES/vimrc/shortcuts.vim

nnoremap ; :
